"""Device (MCU) definitions for the 740 family.

Devices are defined as a small hierarchy: a group base may be inherited by
its parts, which add or override symbols.  _define() merges a parent's
vector table, symbol table, and unsupported-opcode set with the child's;
_finalize() resolves every public device into the flat Devices mapping
(vector_table / symbol_table / unsupported_opcodes) the rest of the tool
uses.  A device may declare unsupported_opcodes (opcodes its core lacks),
which the decoder renders as data; the default empty set changes nothing.
"""

from m740dasm.symbols import Symbol

Devices = {}
_DEFS = {}


def _define(name, parent=None, vector_table=None, symbols=(),
            unsupported_opcodes=(), public=True):
    if name in _DEFS:
        raise ValueError("device %r is already defined" % name)
    if parent is not None:
        base = _DEFS[parent]
        vectors = vector_table if vector_table is not None else base["vectors"]
        by_addr = dict(base["by_addr"])
        unsupported = set(base["unsupported"])
    else:
        vectors = vector_table
        by_addr = {}
        unsupported = set()
    for sym in symbols:
        by_addr[sym.address] = sym
    unsupported.update(unsupported_opcodes)
    _DEFS[name] = {"vectors": vectors, "by_addr": by_addr,
                   "unsupported": frozenset(unsupported), "public": public}


def _finalize():
    for name, d in _DEFS.items():
        if not d["public"]:
            continue
        Devices[name] = {
            "vector_table": list(d["vectors"]),
            "symbol_table": [d["by_addr"][a] for a in sorted(d["by_addr"])],
            "unsupported_opcodes": d["unsupported"],
        }


_define("7450",
    vector_table=[
        0xffe0,
        0xffe2,
        0xffe4,
        0xffe6,
        0xffe8,
        0xffea,
        0xffec,
        0xffee,
        0xfff0,
        0xfff2,
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
        0xfffe,
    ],
    symbols=[
        Symbol(0x00d0, 'P0', 'Port P0'),
        Symbol(0x00d1, 'P0D', 'Port P0 directional register'),
        Symbol(0x00d2, 'P1', 'Port P1'),
        Symbol(0x00d3, 'P1D', 'Port P1 directional register'),
        Symbol(0x00d4, 'P2', 'Port P2'),
        Symbol(0x00d5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00d6, 'P3', 'Port P3'),
        Symbol(0x00d7, 'P3D', 'Port P3 directional register'),
        Symbol(0x00d8, 'P4', 'Port P4'),
        Symbol(0x00d9, 'RESERV', 'Reserved'),
        Symbol(0x00da, 'P5', 'Port P5'),
        Symbol(0x00db, 'P5D', 'Port P5 directional register'),
        Symbol(0x00dc, 'P6', 'Port P6'),
        Symbol(0x00dd, 'P6D', 'Port P6 directional register'),
        Symbol(0x00de, 'MISRG1', 'Miscellaneous register 1'),
        Symbol(0x00df, 'MISRG2', 'Miscellaneous register 2'),
        Symbol(0x00e0, 'DA1', 'D-A1 conversion register'),
        Symbol(0x00e1, 'DA2', 'D-A2 conversion register'),
        Symbol(0x00e2, 'AD', 'A-D conversion register'),
        Symbol(0x00e3, 'ADCNT', 'A-D control register'),
        Symbol(0x00e4, 'DBB', 'Data bus buffer register'),
        Symbol(0x00e5, 'DBBSTS', 'Data bus buffer status register'),
        Symbol(0x00e6, 'RTB', 'Receive/Transmit buffer register'),
        Symbol(0x00e7, 'SIOSTS', 'Serial I/O status register'),
        Symbol(0x00e8, 'SIOCON', 'Serial I/O control register'),
        Symbol(0x00e9, 'UARTCON', 'UART control register'),
        Symbol(0x00ea, 'BRG', 'Baud rate generator'),
        Symbol(0x00eb, 'PWML', 'PWM register (low-order)'),
        Symbol(0x00ec, 'PWMH', 'PWM register (high-order)'),
        Symbol(0x00ed, 'T1CON', 'Timer 1 control register'),
        Symbol(0x00ee, 'T2CON', 'Timer 2 control register'),
        Symbol(0x00ef, 'T3CON', 'Timer 3 control register'),
        Symbol(0x00f0, 'T1L', 'Timer 1 register (low-order)'),
        Symbol(0x00f1, 'T1H', 'Timer 1 register (high-order)'),
        Symbol(0x00f2, 'T1LATL', 'Timer 1 latch (low-order)'),
        Symbol(0x00f3, 'T1LATH', 'Timer 1 latch (high-order)'),
        Symbol(0x00f4, 'T2L', 'Timer 2 register (low-order)'),
        Symbol(0x00f5, 'T2H', 'Timer 2 register (high-order)'),
        Symbol(0x00f6, 'T2LATL', 'Timer 2 latch (low-order)'),
        Symbol(0x00f7, 'T2LATH', 'Timer 2 latch (high-order)'),
        Symbol(0x00f8, 'T3L', 'Timer 3 register (low-order)'),
        Symbol(0x00f9, 'T3H', 'Timer 3 register (high-order)'),
        Symbol(0x00fa, 'T3LATL', 'Timer 3 latch (low-order)'),
        Symbol(0x00fb, 'T3LATH', 'Timer 3 latch (high-order)'),
        Symbol(0x00fc, 'IREQ1', 'Interrupt request register 1'),
        Symbol(0x00fd, 'IREQ2', 'Interrupt request register 2'),
        Symbol(0x00fe, 'ICON1', 'Interrupt control register 1'),
        Symbol(0x00ff, 'ICON2', 'Interrupt control register 2'),
        Symbol(0xffe0, 'INT_BRK', 'BRK instruction'),
        Symbol(0xffe2, 'INT_FFE2_ADC', 'A-D conversion completion flag'),
        Symbol(0xffe4, 'INT_FFE4_SIOTX', 'Serial I/O transmit'),
        Symbol(0xffe6, 'INT_FFE6_SIORX', 'Serial I/O receive'),
        Symbol(0xffe8, 'INT_FFE8_EVENT3', 'EV3 (External event 3)'),
        Symbol(0xffea, 'INT_FFEA_EVENT2', 'EV2 (External event 2)'),
        Symbol(0xffec, 'INT_FFEC_EVENT1', 'EV1 (External event 1)'),
        Symbol(0xffee, 'INT_FFEE_TIMER3', 'Timer 3'),
        Symbol(0xfff0, 'INT_FFF0_TIMER2', 'Timer 2'),
        Symbol(0xfff2, 'INT_FFF2_TIMER1', 'Timer 1'),
        Symbol(0xfff4, 'INT_FFF4_INT3', 'INT3 (External interrupt 3)'),
        Symbol(0xfff6, 'INT_FFF6_INT2', 'INT2 (External interrupt 2)'),
        Symbol(0xfff8, 'INT_FFF8_INT1', 'INT1 (External interrupt 1)'),
        Symbol(0xfffa, 'INT_FFFA_OBE', 'Output buffer empty (OBE)'),
        Symbol(0xfffc, 'INT_FFFC_IBF', 'Input buffer full (IBF)'),
        Symbol(0xfffe, 'RESET', 'Reset vector'),
    ],
)

_define("7451", parent="7450",
    symbols=[
        Symbol(0x00d8, 'P4', 'Port P4 / PWM prescaler latch'),
        Symbol(0x00d9, 'AFD', 'Additional function register'),
    ],
)

_define("_m3800",
    vector_table=[
        0xffdc,
        0xffde,
        0xffe0,
        0xffe2,
        0xffe4,
        0xffe6,
        0xffe8,
        0xffea,
        0xffec,
        0xffee,
        0xfff0,
        0xfff2,
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
    ],
    symbols=[
        Symbol(0x0000, 'P0', 'Port P0'),
        Symbol(0x0001, 'P0D', 'Port P0 direction register'),
        Symbol(0x0002, 'P1', 'Port P1'),
        Symbol(0x0003, 'P1D', 'Port P1 direction register'),
        Symbol(0x0004, 'P2', 'Port P2'),
        Symbol(0x0005, 'P2D', 'Port P2 direction register'),
        Symbol(0x0006, 'P3', 'Port P3'),
        Symbol(0x0007, 'P3D', 'Port P3 direction register'),
        Symbol(0x0008, 'P4', 'Port P4'),
        Symbol(0x0009, 'P4D', 'Port P4 direction register'),
        Symbol(0x000a, 'P5', 'Port P5'),
        Symbol(0x000b, 'P5D', 'Port P5 direction register'),
        Symbol(0x000c, 'P6', 'Port P6'),
        Symbol(0x000d, 'P6D', 'Port P6 direction register'),
        Symbol(0x0018, 'TB_RB', 'Transmit/Receive buffer register'),
        Symbol(0x0019, 'SIO1STS', 'Serial I/O1 status register'),
        Symbol(0x001a, 'SIO1CON', 'Serial I/O1 control register'),
        Symbol(0x001b, 'UARTCON', 'UART control register'),
        Symbol(0x001c, 'BRG', 'Baud rate generator'),
        Symbol(0x001f, 'SIO2', 'Serial I/O2 register'),
        Symbol(0x0036, 'DA1', 'D-A1 conversion register'),
        Symbol(0x0037, 'DA2', 'D-A2 conversion register'),
        Symbol(0x003a, 'INTEDGE', 'Interrupt edge selection register'),
        Symbol(0x003b, 'CPUM', 'CPU mode register'),
        Symbol(0x003c, 'IREQ1', 'Interrupt request register 1'),
        Symbol(0x003d, 'IREQ2', 'Interrupt request register 2'),
        Symbol(0x003e, 'ICON1', 'Interrupt control register 1'),
        Symbol(0x003f, 'ICON2', 'Interrupt control register 2'),
        Symbol(0xffdc, 'INT_BRK', 'BRK instruction interrupt'),
        Symbol(0xfff0, 'INT_FFF0', 'Timer Y'),
        Symbol(0xfff2, 'INT_FFF2', 'Timer X'),
        Symbol(0xfff6, 'INT_FFF6', 'Serial I/O 1 reception'),
        Symbol(0xfffc, 'RESET', 'Reset vector'),
    ],
    public=False,
)

_define("M3802", parent="_m3800",
    symbols=[
        Symbol(0x001d, 'SIO2CON', 'Serial I/O2 control register'),
        Symbol(0x0020, 'PRE12', 'Prescaler 12'),
        Symbol(0x0021, 'T1', 'Timer 1'),
        Symbol(0x0022, 'T2', 'Timer 2'),
        Symbol(0x0023, 'TM', 'Timer XY mode register'),
        Symbol(0x0024, 'PREX', 'Prescaler X'),
        Symbol(0x0025, 'TX', 'Timer X'),
        Symbol(0x0026, 'PREY', 'Prescaler Y'),
        Symbol(0x0027, 'TY', 'Timer Y'),
        Symbol(0x002b, 'PWMCON', 'PWM control register'),
        Symbol(0x002c, 'PREPWM', 'PWM prescaler'),
        Symbol(0x002d, 'PWM', 'PWM register'),
        Symbol(0x0034, 'ADCON', 'AD/DA control register'),
        Symbol(0x0035, 'AD', 'A-D conversion register'),
        Symbol(0xffde, 'INT_FFDE', 'A-D converter'),
        Symbol(0xffe0, 'INT_FFE0', 'INT4'),
        Symbol(0xffe2, 'INT_FFE2', 'INT3'),
        Symbol(0xffe4, 'INT_FFE4', 'INT2'),
        Symbol(0xffe6, 'INT_FFE6', 'Serial I/O 2'),
        Symbol(0xffe8, 'INT_FFE8', 'CNTR1'),
        Symbol(0xffea, 'INT_FFEA', 'CNTR0'),
        Symbol(0xffec, 'INT_FFEC', 'Timer 2'),
        Symbol(0xffee, 'INT_FFEE', 'Timer 1'),
        Symbol(0xfff4, 'INT_FFF4', 'Serial I/O 1 transmission'),
        Symbol(0xfff8, 'INT_FFF8', 'INT1'),
        Symbol(0xfffa, 'INT_FFFA', 'INT0'),
    ],
)

_define("M3807", parent="_m3800",
    symbols=[
        Symbol(0x000e, 'P7', 'Port P7'),
        Symbol(0x000f, 'P7D', 'Port P7 direction register'),
        Symbol(0x0010, 'P8', 'Port P8'),
        Symbol(0x0011, 'P8D', 'Port P8 direction register'),
        Symbol(0x0014, 'TXYCON', 'Timer XY control register'),
        Symbol(0x0015, 'P2P3C', 'Port P2P3 control register'),
        Symbol(0x0016, 'PULL', 'Pull-up control register'),
        Symbol(0x0017, 'WDTCON', 'Watchdog timer control register'),
        Symbol(0x001d, 'SIO2CON1', 'Serial I/O2 control register 1'),
        Symbol(0x001e, 'SIO2CON2', 'Serial I/O2 control register 2'),
        Symbol(0x0020, 'TXL', 'Timer X (low-order)'),
        Symbol(0x0021, 'TXH', 'Timer X (high-order)'),
        Symbol(0x0022, 'TYL', 'Timer Y (low-order)'),
        Symbol(0x0023, 'TYH', 'Timer Y (high-order)'),
        Symbol(0x0024, 'T1', 'Timer 1'),
        Symbol(0x0025, 'T2', 'Timer 2'),
        Symbol(0x0026, 'T3', 'Timer 3'),
        Symbol(0x0027, 'TXM', 'Timer X mode register'),
        Symbol(0x0028, 'TYM', 'Timer Y mode register'),
        Symbol(0x0029, 'T123M', 'Timer 123 mode register'),
        Symbol(0x002a, 'RTP', 'Real time port register'),
        Symbol(0x002b, 'RTPCON0', 'Real time port control register 0'),
        Symbol(0x002c, 'RTPCON1', 'Real time port control register 1'),
        Symbol(0x002d, 'RTPCON2', 'Real time port control register 2'),
        Symbol(0x002e, 'RTPCON3', 'Real time port control register 3'),
        Symbol(0x002f, 'TAL', 'Timer A (low-order)'),
        Symbol(0x0030, 'TAH', 'Timer A (high-order)'),
        Symbol(0x0031, 'TBL', 'Timer B (low-order)'),
        Symbol(0x0032, 'TBH', 'Timer B (high-order)'),
        Symbol(0x0033, 'DACON', 'D-A control register'),
        Symbol(0x0034, 'ADCON', 'A-D control register'),
        Symbol(0x0035, 'AD', 'A-D conversion register'),
        Symbol(0x0038, 'DA3', 'D-A3 conversion register'),
        Symbol(0x0039, 'DA4', 'D-A4 conversion register'),
        Symbol(0xffde, 'INT_FFDE', 'A-D converter / ADT'),
        Symbol(0xffe0, 'INT_FFE0', 'Timer B'),
        Symbol(0xffe2, 'INT_FFE2', 'Timer A'),
        Symbol(0xffe4, 'INT_FFE4', 'INT2 / Timer 1'),
        Symbol(0xffe6, 'INT_FFE6', 'Serial I/O 2'),
        Symbol(0xffe8, 'INT_FFE8', 'CNTR1'),
        Symbol(0xffea, 'INT_FFEA', 'CNTR0'),
        Symbol(0xffec, 'INT_FFEC', 'INT4 / Timer 3'),
        Symbol(0xffee, 'INT_FFEE', 'INT3 / Timer 2'),
        Symbol(0xfff4, 'INT_FFF4', 'Serial I/O 2 transmission'),
        Symbol(0xfff8, 'INT_FFF8', 'INT1'),
        Symbol(0xfffa, 'INT_FFFA', 'INT0'),
    ],
)

_define("M3886", parent="_m3800",
    symbols=[
        Symbol(0x000e, 'P7', 'Port P7'),
        Symbol(0x000f, 'P7D', 'Port P7 direction register'),
        Symbol(0x0010, 'P8_P4I', 'Port P8 / Port P4 input register'),
        Symbol(0x0011, 'P8D_P7I', 'Port P8 direction register / Port P7 input register'),
        Symbol(0x0012, 'S0', 'I2C data shift register'),
        Symbol(0x0013, 'S0D', 'I2C address register'),
        Symbol(0x0014, 'S1', 'I2C status register'),
        Symbol(0x0015, 'S1D', 'I2C control register'),
        Symbol(0x0016, 'S2', 'I2C clock control register'),
        Symbol(0x0017, 'S2D', 'I2C start/stop condition control register'),
        Symbol(0x001d, 'SIO2CON', 'Serial I/O2 control register'),
        Symbol(0x001e, 'WDTCON', 'Watchdog timer control register'),
        Symbol(0x0020, 'PRE12', 'Prescaler 12'),
        Symbol(0x0021, 'T1', 'Timer 1'),
        Symbol(0x0022, 'T2', 'Timer 2'),
        Symbol(0x0023, 'TM', 'Timer XY mode register'),
        Symbol(0x0024, 'PREX', 'Prescaler X'),
        Symbol(0x0025, 'TX', 'Timer X'),
        Symbol(0x0026, 'PREY', 'Prescaler Y'),
        Symbol(0x0027, 'TY', 'Timer Y'),
        Symbol(0x0028, 'DBB0', 'Data bus buffer register 0'),
        Symbol(0x0029, 'DBBSTS0', 'Data bus buffer status register 0'),
        Symbol(0x002a, 'DBBCON', 'Data bus buffer control register'),
        Symbol(0x002b, 'DBB1', 'Data bus buffer register 1'),
        Symbol(0x002c, 'DBBSTS1', 'Data bus buffer status register 1'),
        Symbol(0x002d, 'CMPD', 'Comparator data register'),
        Symbol(0x002e, 'PCTL1', 'Port control register 1'),
        Symbol(0x002f, 'PCTL2', 'Port control register 2'),
        Symbol(0x0030, 'PWM0H', 'PWM0H register'),
        Symbol(0x0031, 'PWM0L', 'PWM0L register'),
        Symbol(0x0032, 'PWM1H', 'PWM1H register'),
        Symbol(0x0033, 'PWM1L', 'PWM1L register'),
        Symbol(0x0034, 'ADCON', 'AD/DA control register'),
        Symbol(0x0035, 'AD1', 'A-D conversion register 1'),
        Symbol(0x0038, 'AD2', 'A-D conversion register 2'),
        Symbol(0x0039, 'INTSEL', 'Interrupt source selection register'),
        Symbol(0x0ffe, 'FCON', 'Flash memory control register'),
        Symbol(0x0fff, 'FCMD', 'Flash command register'),
        Symbol(0xffde, 'INT_FFDE', 'A-D converter / Key-on wake-up'),
        Symbol(0xffe0, 'INT_FFE0', 'INT4'),
        Symbol(0xffe2, 'INT_FFE2', 'INT3'),
        Symbol(0xffe4, 'INT_FFE4', 'INT2 / I2C'),
        Symbol(0xffe6, 'INT_FFE6', 'Serial I/O 2 / I2C'),
        Symbol(0xffe8, 'INT_FFE8', 'CNTR1 / Key-on wake-up'),
        Symbol(0xffea, 'INT_FFEA', 'CNTR0 / SCL, SDA'),
        Symbol(0xffec, 'INT_FFEC', 'Timer 2'),
        Symbol(0xffee, 'INT_FFEE', 'Timer 1'),
        Symbol(0xfff4, 'INT_FFF4', 'Serial I/O 2 transmission / SCL, SDA'),
        Symbol(0xfff8, 'INT_FFF8', 'INT1 / Output buffer empty (OBE)'),
        Symbol(0xfffa, 'INT_FFFA', 'INT0 / Input buffer full (IBF)'),
    ],
)

_define("50734",
    vector_table=[
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
        0xfffe,
    ],
    symbols=[
        Symbol(0x00da, 'TXL', 'Timer X (lower byte)'),
        Symbol(0x00db, 'TXH', 'Timer X (higher byte)'),
        Symbol(0x00dc, 'PRE1', 'Prescaler 1'),
        Symbol(0x00dd, 'T1', 'Timer 1'),
        Symbol(0x00de, 'PRE2', 'Prescaler 2'),
        Symbol(0x00df, 'T2', 'Timer 2'),
        Symbol(0x00e0, 'PRE3', 'Prescaler 3'),
        Symbol(0x00e1, 'T3', 'Timer 3'),
        Symbol(0x00e2, 'HCNT', 'Horizontal counter'),
        Symbol(0x00e3, 'VCNT', 'Vertical counter'),
        Symbol(0x00e4, 'TSR', 'Transmit shift register'),
        Symbol(0x00e5, 'RBR', 'Receive buffer register'),
        Symbol(0x00e6, 'UCON', 'UART control register'),
        Symbol(0x00e7, 'USR', 'UART status register'),
        Symbol(0x00e8, 'SIO', 'Serial I/O register'),
        Symbol(0x00e9, 'ADCON', 'A-D control register'),
        Symbol(0x00ea, 'ADR', 'A-D register'),
        Symbol(0x00eb, 'P4IN', 'Port P4 input'),
        Symbol(0x00ec, 'PHASECNT', 'Vertical + Horizontal phase counter'),
        Symbol(0x00ed, 'P2P3FUNC', 'Port P2 P3 function register'),
        Symbol(0x00ee, 'P3', 'Port P3'),
        Symbol(0x00ef, 'P3DIR', 'Port P3 directional register'),
        Symbol(0x00f0, 'P2', 'Port P2'),
        Symbol(0x00f1, 'P2DIR', 'Port P2 directional register'),
        Symbol(0x00f2, 'P1IN', 'Port P1 latch input'),
        Symbol(0x00f3, 'P1', 'Port P1'),
        Symbol(0x00f4, 'P1DIR', 'Port P1 directional register'),
        Symbol(0x00f5, 'P0FUNC', 'Port P0 function register'),
        Symbol(0x00f6, 'P0', 'Port P0'),
        Symbol(0x00f7, 'P0DIR', 'Port P0 directional register'),
        Symbol(0x00f8, 'SMCONH', 'Stepper motor control register H'),
        Symbol(0x00f9, 'SMCONV', 'Stepper motor control register V'),
        Symbol(0x00fa, 'STBT', 'Strobe timer (Timer S)'),
        Symbol(0x00fb, 'BRGTB', 'Baud rate generator (Timer B)'),
        Symbol(0x00fc, 'WDT', 'Watchdog timer (Timer W)'),
        Symbol(0x00fd, 'ICON3', 'Interrupt control register 3'),
        Symbol(0x00fe, 'ICON2', 'Interrupt control register 2'),
        Symbol(0x00ff, 'ICON1', 'Interrupt control register 1'),
        Symbol(0xfff4, 'INT_FFF4_TXCNTRBRK', 'TX, CNTR, or BRK'),
        Symbol(0xfff6, 'INT_FFF6_HEVE', 'HE or VE'),
        Symbol(0xfff8, 'INT_FFF8_T1T2T3', 'Timer1, Timer2, or Timer3'),
        Symbol(0xfffa, 'INT_FFFA_RI_INT1', 'RI or INT1'),
        Symbol(0xfffc, 'INT_FFFC_INT2', 'INT2 (External interrupt 2)'),
        Symbol(0xfffe, 'RESET', 'Reset vector'),
    ],
)


# --- Auto-generated MELPS 740 device entries (NEW chips only) ---
# Addresses/vectors/descriptions are datasheet-derived; SFR symbol NAMES are
# heuristic and may be refined.  No entry here overlaps the hand-curated
# devices above (enforced by the guards in _define/_alias).

# M50740A-XXXSP/FP  (SFR PDF p50, vectors PDF p50)
_define("50740A",
    vector_table=[
        0x1ff4,
        0x1ff6,
        0x1ff8,
        0x1ffa,
        0x1ffc,
        0x1ffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e1, 'P0D', 'Port P0 directional register'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e3, 'P1D', 'Port P1 directional register'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00f9, 'PRE12', 'Timer 1,2 prescaler'),
        Symbol(0x00fa, 'T1', 'Timer 1'),
        Symbol(0x00fb, 'T2', 'Timer 2'),
        Symbol(0x00fc, 'PREX', 'Timer X prescaler'),
        Symbol(0x00fd, 'TX', 'Timer X'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0x1ff4, 'INT_1FF4_INT', 'INT'),
        Symbol(0x1ff6, 'INT_1FF6_TIMER2', 'Timer 2'),
        Symbol(0x1ff8, 'INT_1FF8_TIMER1', 'Timer 1'),
        Symbol(0x1ffa, 'INT_1FFA_TIMERX', 'Timer X'),
        Symbol(0x1ffc, 'INT_1FFC_CNTR', 'CNTR'),
        Symbol(0x1ffe, 'RESET', 'Reset vector'),
    ],
)

# M50742-XXXSP/FP  (SFR PDF p75, vectors PDF p75)
_define("50742",
    vector_table=[
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
        0xfffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e1, 'P0D', 'Port P0 directional register'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e3, 'P1D', 'Port P1 directional register'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00eb, 'P4D', 'Port P4 directional register'),
        Symbol(0x00ec, 'P5', 'Port P5'),
        Symbol(0x00ee, 'P6', 'Port P6'),
        Symbol(0x00f6, 'SIOMR', 'Serial I/O mode register'),
        Symbol(0x00f7, 'SIOR', 'Serial I/O register'),
        Symbol(0x00f9, 'PRE12', 'Timer 1, 2 prescaler'),
        Symbol(0x00fa, 'T1', 'Timer 1'),
        Symbol(0x00fb, 'T2', 'Timer 2'),
        Symbol(0x00fc, 'PREX', 'Timer X prescaler'),
        Symbol(0x00fd, 'TX', 'Timer X'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0xfff4, 'INT_FFF4_INT2', 'INT2'),
        Symbol(0xfff6, 'INT_FFF6_SIOORTIMER', 'S I/O or Timer 2'),
        Symbol(0xfff8, 'INT_FFF8_TIMER1', 'Timer 1'),
        Symbol(0xfffa, 'INT_FFFA_TIMERX', 'Timer X'),
        Symbol(0xfffc, 'INT_FFFC_INT1', 'INT1'),
        Symbol(0xfffe, 'RESET', 'Reset vector'),
    ],
)

# M50743-XXXSP/FP  (SFR PDF p101, vectors PDF p101)
_define("50743",
    vector_table=[
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
        0xfffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e1, 'P0D', 'Port P0 directional register'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e3, 'P1D', 'Port P1 directional register'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00eb, 'P4D', 'Port P4 directional register'),
        Symbol(0x00ec, 'P5', 'Port P5'),
        Symbol(0x00ee, 'P6', 'Port P6'),
        Symbol(0x00f6, 'SIOMR', 'Serial I/O mode register'),
        Symbol(0x00f7, 'SIOR', 'Serial I/O register'),
        Symbol(0x00f9, 'PRE12', 'Timer 1,2 prescaler'),
        Symbol(0x00fa, 'T1', 'Timer 1'),
        Symbol(0x00fb, 'T2', 'Timer 2'),
        Symbol(0x00fc, 'PREX', 'Timer X prescaler'),
        Symbol(0x00fd, 'TX', 'Timer X'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0xfff4, 'INT_FFF4_INT2', 'INT2'),
        Symbol(0xfff6, 'INT_FFF6_SIOORTIMER', 'S I/O or Timer 2'),
        Symbol(0xfff8, 'INT_FFF8_TIMER1', 'Timer 1'),
        Symbol(0xfffa, 'INT_FFFA_TIMERX', 'Timer X'),
        Symbol(0xfffc, 'INT_FFFC_INT1', 'INT1'),
        Symbol(0xfffe, 'RESET', 'Reset vector'),
    ],
)

# M50744-XXXSP/FP  (SFR PDF p127, vectors PDF p127)
_define("50744",
    vector_table=[
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
        0xfffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e1, 'P0D', 'Port P0 directional register'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e3, 'P1D', 'Port P1 directional register'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional, register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00eb, 'P4D', 'Port P4 directional register'),
        Symbol(0x00ec, 'P5', 'Port P5'),
        Symbol(0x00ed, 'P5_2', 'Port P5 latch'),
        Symbol(0x00ee, 'P6', 'Port P6'),
        Symbol(0x00f0, 'DACR', 'D-A conversion register'),
        Symbol(0x00f1, 'PWMR', 'Pulse width modulation register'),
        Symbol(0x00f2, 'SAR', 'Successive approximation register'),
        Symbol(0x00f3, 'ADCR', 'A-D control register'),
        Symbol(0x00f4, 'WT', 'Watchdog timer'),
        Symbol(0x00f9, 'PRE12', 'Timer 1,2 prescaler'),
        Symbol(0x00fa, 'T1', 'Timer 1'),
        Symbol(0x00fb, 'T2', 'Timer 2'),
        Symbol(0x00fc, 'PREX', 'Timer X prescaler'),
        Symbol(0x00fd, 'TX', 'Timer X'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0xfff4, 'INT_FFF4_INT2', 'INT2'),
        Symbol(0xfff6, 'INT_FFF6_TIMER2', 'Timer 2'),
        Symbol(0xfff8, 'INT_FFF8_TIMER1', 'Timer 1'),
        Symbol(0xfffa, 'INT_FFFA_TIMERX', 'Timer X'),
        Symbol(0xfffc, 'INT_FFFC_INT1', 'INT1'),
        Symbol(0xfffe, 'RESET', 'Reset vector'),
    ],
)

# M50745-XXXSP/FP  (SFR PDF p155, vectors PDF p155)
_define("50745",
    vector_table=[
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
        0xfffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e1, 'P0D', 'Port P0 directional register'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e3, 'P1D', 'Port P1 directional register'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00eb, 'P4D', 'Port P4 directional register'),
        Symbol(0x00ec, 'P5', 'Port P5'),
        Symbol(0x00f6, 'SIOMR', 'Serial I/O mode register'),
        Symbol(0x00f7, 'SIOR', 'Serial I/O register'),
        Symbol(0x00f9, 'PRE12', 'Timer 1,2 prescaler'),
        Symbol(0x00fa, 'T1', 'Timer 1'),
        Symbol(0x00fb, 'T2', 'Timer 2'),
        Symbol(0x00fc, 'PREX', 'Timer X prescaler'),
        Symbol(0x00fd, 'TX', 'Timer X'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0xfff4, 'INT_FFF4_INT2', 'INT2'),
        Symbol(0xfff6, 'INT_FFF6_SIOORTIMER', 'S I/O or Timer 2'),
        Symbol(0xfff8, 'INT_FFF8_TIMER1', 'Timer 1'),
        Symbol(0xfffa, 'INT_FFFA_TIMERX', 'Timer X'),
        Symbol(0xfffc, 'INT_FFFC_INT1', 'INT1'),
        Symbol(0xfffe, 'RESET', 'Reset vector'),
    ],
)

# M50747-XXXSP/FP  (SFR PDF p181, vectors PDF p181)
_define("50747",
    vector_table=[
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
        0xfffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e1, 'P0D', 'Port P0 directional register'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e3, 'P1D', 'Port P1 directional register'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00eb, 'P4D', 'Port P4 directional register'),
        Symbol(0x00ec, 'P5', 'Port P5'),
        Symbol(0x00ee, 'P6', 'Port P6'),
        Symbol(0x00f4, 'TRMR', 'Transmit/Receive mode register'),
        Symbol(0x00f5, 'TRCR', 'Transmit/Receive control register'),
        Symbol(0x00f6, 'TR', 'Transmit register'),
        Symbol(0x00f7, 'RBR', 'Receive buffer register'),
        Symbol(0x00f9, 'PRE12', 'Timer 1,2 prescaler'),
        Symbol(0x00fa, 'T1', 'Timer 1'),
        Symbol(0x00fb, 'T2', 'Timer 2'),
        Symbol(0x00fc, 'PREX', 'Timer X prescaler'),
        Symbol(0x00fd, 'TX', 'Timer X'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0xfff4, 'INT_FFF4_INT', ''),
        Symbol(0xfff6, 'INT_FFF6_INT2SIOORT', 'INT2 S I/O or Timer 2'),
        Symbol(0xfff8, 'INT_FFF8_TIMER1', 'Timer 1'),
        Symbol(0xfffa, 'INT_FFFA_TIMERX', 'Timer X'),
        Symbol(0xfffc, 'INT_FFFC_INT1', 'INT1'),
        Symbol(0xfffe, 'RESET', 'Reset vector'),
    ],
)

# M50752-XXXSP  (SFR PDF p222, vectors PDF p222)
_define("50752",
    vector_table=[
        0x1ff4,
        0x1ff6,
        0x1ff8,
        0x1ffa,
        0x1ffc,
        0x1ffe,
    ],
    symbols=[
        Symbol(0x00df, 'PR', 'Port R'),
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e1, 'P0D', 'Port P0 directional register'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00f9, 'PRE12', 'Timer 1,2 prescaler'),
        Symbol(0x00fa, 'T1', 'Timer 1'),
        Symbol(0x00fb, 'T2', 'Timer 2'),
        Symbol(0x00fc, 'PREX', 'Timer X Prescaler'),
        Symbol(0x00fd, 'TX', 'Timer X'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0x1ff4, 'INT_1FF4_INT', ''),
        Symbol(0x1ff6, 'INT_1FF6_INT1TIMER2', 'INT1 Timer 2'),
        Symbol(0x1ff8, 'INT_1FF8_TIMER1', 'Timer 1'),
        Symbol(0x1ffa, 'INT_1FFA_TIMERX', 'Timer X'),
        Symbol(0x1ffc, 'INT_1FFC_INT2', 'INT2'),
        Symbol(0x1ffe, 'RESET', 'Reset vector'),
    ],
)

# M50753-XXXSP/FP  (SFR PDF p246, vectors PDF p246)
_define("50753",
    vector_table=[
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
        0xfffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e1, 'P0D', 'Port P0 directional register'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e3, 'P1D', 'Port P1 directional register'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00eb, 'P4D', 'Port P4 directional register'),
        Symbol(0x00ee, 'IR', 'IN register'),
        Symbol(0x00ef, 'ADR', 'A-D register'),
        Symbol(0x00f2, 'ADSA', 'A-D start address'),
        Symbol(0x00f3, 'ADCR', 'A-D control register'),
        Symbol(0x00f5, 'PCR', 'PWM control register'),
        Symbol(0x00f6, 'SIOMR', 'Serial I/O mode register'),
        Symbol(0x00f7, 'SIOR', 'Serial I/O register'),
        Symbol(0x00f9, 'PRE12', 'Timer 1, 2 prescaler'),
        Symbol(0x00fa, 'T1', 'Timer 1'),
        Symbol(0x00fb, 'T2', 'Timer 2'),
        Symbol(0x00fc, 'PREX', 'Timer X prescaler'),
        Symbol(0x00fd, 'TX', 'Timer X'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0xfff4, 'INT_FFF4_INT2', 'INT2'),
        Symbol(0xfff6, 'INT_FFF6_SIOORTIMER', 'S I/O or Timer 2'),
        Symbol(0xfff8, 'INT_FFF8_TIMER1ORAD', 'Timer 1 or A-D'),
        Symbol(0xfffa, 'INT_FFFA_TIMERX', 'Timer X'),
        Symbol(0xfffc, 'INT_FFFC_INT1', 'INT1'),
        Symbol(0xfffe, 'RESET', 'Reset vector'),
    ],
)

# M50754-XXXSP/FP/GP  (SFR PDF p276, vectors PDF p276)
_define("50754",
    vector_table=[
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
        0xfffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00ec, 'P5', 'Port P5'),
        Symbol(0x00ee, 'P6', 'Port P6'),
        Symbol(0x00ef, 'P6D', 'Port P6 directional register'),
        Symbol(0x00f0, 'PHR', 'PWM1-H register'),
        Symbol(0x00f1, 'PLR', 'PWM1-L register'),
        Symbol(0x00f2, 'PR', 'PWM2 register'),
        Symbol(0x00f3, 'PR_2', 'PWM3 register'),
        Symbol(0x00f5, 'POMR', 'PWM output mode register'),
        Symbol(0x00f6, 'SIOMR', 'Serial I/O mode register'),
        Symbol(0x00f7, 'SIOR', 'Serial I/O register'),
        Symbol(0x00fa, 'T1', 'Timer 1'),
        Symbol(0x00fc, 'T2', 'Timer 2'),
        Symbol(0x00fd, 'T3', 'Timer 3'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0xfff4, 'INT_FFF4_INT2', 'INT2'),
        Symbol(0xfff6, 'INT_FFF6_SIOORTIMER', 'S I/O or Timer 1'),
        Symbol(0xfff8, 'INT_FFF8_TIMER2', 'Timer 2'),
        Symbol(0xfffa, 'INT_FFFA_TIMER3', 'Timer 3'),
        Symbol(0xfffc, 'INT_FFFC_INT1', 'INT1'),
        Symbol(0xfffe, 'RESET', 'Reset vector'),
    ],
)

# M50930-XXXFP  (SFR PDF p312, vectors PDF p312)
_define("50930",
    vector_table=[
        0x3ff4,
        0x3ff6,
        0x3ff8,
        0x3ffa,
        0x3ffc,
        0x3ffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e1, 'P0D', 'Port P0 directional register'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e3, 'P1D', 'Port P1 directional register'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00f5, 'LMR', 'LCD mode register'),
        Symbol(0x00f6, 'SIOMR', 'Serial I/O mode register'),
        Symbol(0x00f7, 'SIOR', 'Serial I/O register'),
        Symbol(0x00f8, 'T4', 'Timer 4,5 mode register'),
        Symbol(0x00f9, 'T1', 'Timer 1'),
        Symbol(0x00fa, 'T2', 'Timer 2'),
        Symbol(0x00fb, 'T3', 'Timer 3'),
        Symbol(0x00fc, 'T4_2', 'Timer 4'),
        Symbol(0x00fd, 'T5', 'Timer 5'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0x3ff4, 'INT_3FF4_INT', ''),
        Symbol(0x3ff6, 'INT_3FF6_INT2SERIAL', 'INT2 Serial I/O'),
        Symbol(0x3ff8, 'INT_3FF8_ORTIMER3TI', 'or Timer 3 Timer 2'),
        Symbol(0x3ffa, 'INT_3FFA_TIMER1', 'Timer 1'),
        Symbol(0x3ffc, 'INT_3FFC_INT1', 'INT1'),
        Symbol(0x3ffe, 'RESET', 'Reset vector'),
    ],
)

# M50940-XXXSP/FP  (SFR PDF p347, vectors PDF p347)
_define("50940",
    vector_table=[
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
        0xfffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00eb, 'P4D', 'Port P4 directional register'),
        Symbol(0x00ec, 'PI', 'Port IN'),
        Symbol(0x00ef, 'ADR', 'A-D register'),
        Symbol(0x00f0, 'PR', 'Port R'),
        Symbol(0x00f2, 'ADSA', 'A-D start address'),
        Symbol(0x00f3, 'ADCR', 'A-D control register'),
        Symbol(0x00f5, 'T4', 'Timer 4, 5 control register'),
        Symbol(0x00f6, 'SIOMR', 'Serial I/O mode register'),
        Symbol(0x00f7, 'SIOR', 'Serial I/O register'),
        Symbol(0x00f9, 'T1', 'Timer 1'),
        Symbol(0x00fa, 'T2', 'Timer 2'),
        Symbol(0x00fb, 'T3', 'Timer 3'),
        Symbol(0x00fc, 'T4_2', 'Timer 4'),
        Symbol(0x00fd, 'T5', 'Timer 5'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0xfff4, 'INT_FFF4_INT', ''),
        Symbol(0xfff6, 'INT_FFF6_INT2SERIAL', 'INT2 Serial I/O or'),
        Symbol(0xfff8, 'INT_FFF8_TIMER3TIME', 'Timer3 Timer2'),
        Symbol(0xfffa, 'INT_FFFA_TIMER1ORAD', 'Timer 1 or A-D'),
        Symbol(0xfffc, 'INT_FFFC_INT1', 'INT1'),
        Symbol(0xfffe, 'RESET', 'Reset vector'),
    ],
)

# M50943-XXXSP/FP  (SFR PDF p380, vectors PDF p380)
_define("50943",
    vector_table=[
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
        0xfffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e1, 'P0D', 'Port P0 directional register'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e3, 'P1D', 'Port P1 directional register'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00eb, 'P4D', 'Port P4 directional register'),
        Symbol(0x00ee, 'IR', 'IN register'),
        Symbol(0x00ef, 'ADR', 'A-D register'),
        Symbol(0x00f2, 'ADSA', 'A-D start address'),
        Symbol(0x00f3, 'ADCR', 'A-D control register'),
        Symbol(0x00f5, 'PCR', 'PWM control register'),
        Symbol(0x00f6, 'SIOMR', 'Serial I/O mode register'),
        Symbol(0x00f7, 'SIOR', 'Serial I/O register'),
        Symbol(0x00f9, 'PRE12', 'Timer 1, 2 prescaler'),
        Symbol(0x00fa, 'T1', 'Timer 1'),
        Symbol(0x00fb, 'T2', 'Timer 2'),
        Symbol(0x00fc, 'PREX', 'Timer X prescaler'),
        Symbol(0x00fd, 'TX', 'Timer X'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0xfff4, 'INT_FFF4_INT2', 'INT2'),
        Symbol(0xfff6, 'INT_FFF6_SIOORTIMER', 'S I/O or timer 2'),
        Symbol(0xfff8, 'INT_FFF8_TIMER1ORAD', 'Timer 1 or A-D'),
        Symbol(0xfffa, 'INT_FFFA_TIMERX', 'Timer X'),
        Symbol(0xfffc, 'INT_FFFC_INT1', 'INT1'),
        Symbol(0xfffe, 'RESET', 'Reset vector'),
    ],
)

# M50944-XXXSP/FP  (SFR PDF p410, vectors PDF p410)
_define("50944",
    vector_table=[
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
        0xfffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e1, 'P0D', 'Port P0 directional register'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e3, 'P1D', 'Port P1 directional register'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00eb, 'P4D', 'Port P4 directional register'),
        Symbol(0x00ec, 'PI', 'Port IN'),
        Symbol(0x00ed, 'PRE4', 'Timer 4 prescaler'),
        Symbol(0x00ee, 'T4', 'Timer 4'),
        Symbol(0x00ef, 'ADR', 'A-D register'),
        Symbol(0x00f0, 'PR', 'Port R'),
        Symbol(0x00f1, 'IRDR1', 'Interrupt request distinguish register1'),
        Symbol(0x00f2, 'IRDR2', 'Interrupt request distinguish register2'),
        Symbol(0x00f3, 'ADCR', 'A-D control register'),
        Symbol(0x00f4, 'SIOMR', 'Serial I/O2 mode register'),
        Symbol(0x00f5, 'SIOR', 'Serial I/O2 register'),
        Symbol(0x00f6, 'SMR', 'Serial 1/01 mode register'),
        Symbol(0x00f7, 'SIOR_2', 'Serial I/O1 register'),
        Symbol(0x00f8, 'SIOCSR', 'Serial I/O2 clock selection register'),
        Symbol(0x00f9, 'PRE3', 'Timer 3 prescaler'),
        Symbol(0x00fa, 'T3', 'Timer 3'),
        Symbol(0x00fb, 'PRE12', 'Timer 1,2 prescaler'),
        Symbol(0x00fc, 'T1', 'Timer 1'),
        Symbol(0x00fd, 'T2', 'Timer 2'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0xfff4, 'INT_FFF4_INT', ''),
        Symbol(0xfff6, 'INT_FFF6_HINT4ORAD', 'H. INT4 or A-D'),
        Symbol(0xfff8, 'INT_FFF8_INT3ORTIME', 'INT3 or Timer 4'),
        Symbol(0xfffa, 'INT_FFFA_INT2ORTIME', 'INT2 or Timer 3 Timer 2 or Serial I/O'),
        Symbol(0xfffc, 'INT_FFFC_INT1ORTIME', 'INT1 or Timer 1'),
        Symbol(0xfffe, 'RESET', 'Reset vector'),
    ],
)

# M50950-XXXSP  (SFR PDF p446, vectors PDF p446)
_define("50950",
    vector_table=[
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
        0xfffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00eb, 'P4D', 'Port P4 directional register'),
        Symbol(0x00ec, 'P5', 'Port P5'),
        Symbol(0x00f4, 'SIOR', 'Serial I/O2 register'),
        Symbol(0x00f5, 'SIOMR', 'Serial I/O2 mode register'),
        Symbol(0x00f6, 'SIOMR_2', 'Serial I/O1 mode register'),
        Symbol(0x00f7, 'SIOR_2', 'Serial I/O1 register'),
        Symbol(0x00fa, 'T1', 'Timer 1'),
        Symbol(0x00fc, 'T2', 'Timer 2'),
        Symbol(0x00fd, 'T3', 'Timer 3'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0xfff4, 'INT_FFF4_INT', ''),
        Symbol(0xfff6, 'INT_FFF6_INT2SIO1OR', 'INT2 S I/O1 or timer 1'),
        Symbol(0xfff8, 'INT_FFF8_TIMER2', 'Timer 2'),
        Symbol(0xfffa, 'INT_FFFA_TIMER3', 'Timer 3'),
        Symbol(0xfffc, 'INT_FFFC_INT1', 'INT1'),
        Symbol(0xfffe, 'RESET', 'Reset vector'),
    ],
)

# M50957-XXXSP/FP  (SFR PDF p479, vectors PDF p479)
_define("50957",
    vector_table=[
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
        0xfffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00ec, 'P5', 'Port P5'),
        Symbol(0x00ee, 'P6', 'Port P6'),
        Symbol(0x00ef, 'P6D', 'Port P6 directional register'),
        Symbol(0x00f0, 'PHR', 'PWM1-H register'),
        Symbol(0x00f1, 'PLR', 'PWM1-L register'),
        Symbol(0x00f2, 'PR', 'PWM2 register'),
        Symbol(0x00f3, 'PR_2', 'PWM3 register'),
        Symbol(0x00f5, 'POMR', 'PWM output mode register'),
        Symbol(0x00f6, 'SIOMR', 'Serial I/O mode register'),
        Symbol(0x00f7, 'SIOR', 'Serial I/O register'),
        Symbol(0x00fa, 'T1', 'Timer 1'),
        Symbol(0x00fb, 'CR', 'Comparator register'),
        Symbol(0x00fc, 'T2', 'Timer 2'),
        Symbol(0x00fd, 'T3', 'Timer 3'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0xfff4, 'INT_FFF4_INT2', 'INT2'),
        Symbol(0xfff6, 'INT_FFF6_SIOORTIMER', 'S I/O or Timer 1'),
        Symbol(0xfff8, 'INT_FFF8_TIMER2', 'Timer 2'),
        Symbol(0xfffa, 'INT_FFFA_TIMER3', 'Timer 3'),
        Symbol(0xfffc, 'INT_FFFC_INT1', 'INT1'),
        Symbol(0xfffe, 'RESET', 'Reset vector'),
    ],
)

# M50964-XXXSP/FP  (SFR PDF p518, vectors PDF p518)
_define("50964",
    vector_table=[
        0xfff4,
        0xfff6,
        0xfff8,
        0xfffa,
        0xfffc,
        0xfffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e1, 'P0D', 'Port P0 directional register'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e3, 'P1D', 'Port P1 directional register'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00eb, 'P4D', 'Port P4 directional register'),
        Symbol(0x00ec, 'P5', 'Port P5'),
        Symbol(0x00ed, 'P5_2', 'Port P5 latch'),
        Symbol(0x00ee, 'P6', 'Port P6'),
        Symbol(0x00ef, 'SFSR', 'Special function selection register'),
        Symbol(0x00f0, 'DACR', 'D-A conversion register'),
        Symbol(0x00f1, 'PWMR', 'Pulse width modulation register'),
        Symbol(0x00f2, 'SAR', 'Successive approximation register'),
        Symbol(0x00f3, 'ADCR', 'A-D control register'),
        Symbol(0x00f4, 'WT', 'Watchdog timer'),
        Symbol(0x00f5, 'SIOMR', 'Serial I/O mode register'),
        Symbol(0x00f6, 'SIOR', 'Serial I/O register'),
        Symbol(0x00f7, 'PRE3', 'Timer 3 prescaler'),
        Symbol(0x00f8, 'T3', 'Timer 3'),
        Symbol(0x00f9, 'PRE12', 'Timer 1,2 prescaler'),
        Symbol(0x00fa, 'T1', 'Timer 1'),
        Symbol(0x00fb, 'T2', 'Timer 2'),
        Symbol(0x00fc, 'PREX', 'Timer X prescaler'),
        Symbol(0x00fd, 'TX', 'Timer X'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0xfff4, 'INT_FFF4_INT2', 'INT2'),
        Symbol(0xfff6, 'INT_FFF6_SIOORTIMER', 'S I/O or timer 2'),
        Symbol(0xfff8, 'INT_FFF8_TIMER1', 'Timer 1'),
        Symbol(0xfffa, 'INT_FFFA_TIMERX', 'Timer X'),
        Symbol(0xfffc, 'INT_FFFC_INT', 'INT,'),
        Symbol(0xfffe, 'RESET', 'Reset vector'),
    ],
)

# M37410M3-XXXFP  (SFR PDF p549, vectors PDF p549)
_define("37410M3",
    vector_table=[
        0x3ff4,
        0x3ff6,
        0x3ff8,
        0x3ffa,
        0x3ffc,
        0x3ffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e1, 'P0D', 'Port P0 directional register'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e3, 'P1D', 'Port P1 directional register'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00eb, 'IDRR1', 'Interrupt distinguish request register 1'),
        Symbol(0x00ec, 'P5', 'Port P5'),
        Symbol(0x00ed, 'P5D', 'Port P5 directional register'),
        Symbol(0x00ee, 'PKOWR', 'P2 Key on wakeup register'),
        Symbol(0x00ef, 'ADR', 'A-D register'),
        Symbol(0x00f0, 'IDRR2', 'Interrupt distinguish request register 2'),
        Symbol(0x00f1, 'T6', 'Timer 6 latch'),
        Symbol(0x00f2, 'ADCR', 'A-D control register'),
        Symbol(0x00f3, 'PCR', 'PWM control register'),
        Symbol(0x00f4, 'SCR', 'Segment control register'),
        Symbol(0x00f5, 'LMR', 'LCD mode register'),
        Symbol(0x00f6, 'SIOMR', 'Serial I/O mode register'),
        Symbol(0x00f7, 'SIOR', 'Serial I/O register'),
        Symbol(0x00f8, 'T4', 'Timer 4, 5 mode register'),
        Symbol(0x00f9, 'T1', 'Timer 1 latch'),
        Symbol(0x00fa, 'T2', 'Timer 2 latch'),
        Symbol(0x00fb, 'T3', 'Timer 3 latch'),
        Symbol(0x00fc, 'T4_2', 'Timer 4 latch'),
        Symbol(0x00fd, 'T5', 'Timer 5 latch'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0x3ff4, 'INT_3FF4_TIMER6ORAD', 'Timer 6 or A-D'),
        Symbol(0x3ff6, 'INT_3FF6_TIMER3ORIN', 'Timer 3 or INT2'),
        Symbol(0x3ff8, 'INT_3FF8_INT3ORKEYO', 'INT3 or Key on wake up'),
        Symbol(0x3ffa, 'INT_3FFA_SERIALIOOR', 'Serial I/O or timer 2'),
        Symbol(0x3ffc, 'INT_3FFC_INT1', 'INT1'),
        Symbol(0x3ffe, 'RESET', 'Reset vector'),
    ],
)

# M37415M4-XXXFP  (SFR PDF p580, vectors PDF p580)
_define("37415M4",
    vector_table=[
        0x3ff4,
        0x3ff6,
        0x3ff8,
        0x3ffa,
        0x3ffc,
        0x3ffe,
    ],
    symbols=[
        Symbol(0x00e0, 'P0', 'Port P0'),
        Symbol(0x00e1, 'P0D', 'Port P0 directional register'),
        Symbol(0x00e2, 'P1', 'Port P1'),
        Symbol(0x00e3, 'P1D', 'Port P1 directional register'),
        Symbol(0x00e4, 'P2', 'Port P2'),
        Symbol(0x00e5, 'P2D', 'Port P2 directional register'),
        Symbol(0x00e8, 'P3', 'Port P3'),
        Symbol(0x00e9, 'P3D', 'Port P3 directional register'),
        Symbol(0x00ea, 'P4', 'Port P4'),
        Symbol(0x00f4, 'DR', 'DTMF register'),
        Symbol(0x00f5, 'LMR', 'LCD mode register'),
        Symbol(0x00f6, 'SIOMR', 'Serial I/O mode register'),
        Symbol(0x00f7, 'SIOR', 'Serial I/O register'),
        Symbol(0x00f8, 'T4', 'Timer 4,5 mode register'),
        Symbol(0x00f9, 'T1', 'Timer 1'),
        Symbol(0x00fa, 'T2', 'Timer 2'),
        Symbol(0x00fb, 'T3', 'Timer 3'),
        Symbol(0x00fc, 'T4_2', 'Timer 4'),
        Symbol(0x00fd, 'T5', 'Timer 5'),
        Symbol(0x00fe, 'ICON', 'Interrupt control register'),
        Symbol(0x00ff, 'TCON', 'Timer control register'),
        Symbol(0x3ff4, 'INT_3FF4_INT', ''),
        Symbol(0x3ff6, 'INT_3FF6_INT2SERIAL', 'INT2 Serial I/O'),
        Symbol(0x3ff8, 'INT_3FF8_ORTIMER3TI', 'or Timer 3 Timer 2'),
        Symbol(0x3ffa, 'INT_3FFA_TIMER1', 'Timer, 1'),
        Symbol(0x3ffc, 'INT_3FFC_INT1', 'INT1'),
        Symbol(0x3ffe, 'RESET', 'Reset vector'),
    ],
)


_finalize()


def _alias(new, base):
    if new in Devices:
        raise ValueError("device alias %r would overwrite an existing entry" % new)
    Devices[new] = Devices[base]


# Aliases
_alias("M37450", "7450")
_alias("M37451", "7451")
_alias("M50734", "50734")

# Variants inheriting a base chip (abbreviated datasheets, no own figure)
_alias("50747H", "50747")
_alias("50734_10", "50734")
_alias("37450S1", "7450")

# Sibling part numbers sharing a datasheet / register map (from the databook)
_alias("37410M4", "37410M3")
_alias("37450M4", "7450")
_alias("37450M8", "7450")
_alias("37450S2", "7450")
_alias("37450S4", "7450")
_alias("50708", "50742")
_alias("50741", "50740A")
_alias("50746", "50744")
_alias("50757", "50752")
_alias("50758", "50752")
_alias("50931", "50930")
_alias("50932", "50930")
_alias("50941", "50940")
_alias("50951", "50950")
_alias("50954", "50754")
_alias("50955", "50754")
_alias("50959", "50957")
_alias("50963", "50964")
